version: '3'

services:
  freeradius:
    image: public.ecr.aws/a0j1s2e9/freeradius:latest
    working_dir: /etc/freeradius
    network_mode: "host"
    volumes:
      - /home/pi/.firewalla/run/docker/freeradius/config:/root/freeradius/config
      - /home/pi/.firewalla/certs/freeradius:/root/.certs
      - /home/pi/.firewalla/config/freeradius:/root/.config
      - /home/pi/.forever/freeradius/:/var/log/freeradius/
    command: bash -c "bash /root/freeradius/freeradius.sh run && tail -f /dev/null"
