version: '3'

services:
  freeradius:
    image: public.ecr.aws/a0j1s2e9/freeradius:latest
    working_dir: /etc/freeradius
    network_mode: "host"
    environment:
      - NODE_PATH=/root/node_modules
    volumes:
      - /home/pi/.firewalla/run/docker/freeradius/config:/root/freeradius/config
      - /home/pi/.firewalla/certs/freeradius:/root/certs
      - /home/pi/.firewalla/config/freeradius:/root/.config
      - /home/pi/.forever/freeradius:/var/log/freeradius
      - /home/pi/.node_modules/node_modules:/root/node_modules
    command: bash -c "bash /root/freeradius/freeradius.sh run && tail -f /dev/null"
